# Generated by Django 5.1.1 on 2025-10-28 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0003_leave_attendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(default='fa-file', help_text='FontAwesome icon class', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Document Category',
                'verbose_name_plural': 'Document Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BiometricAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('check_in', 'Check In'), ('check_out', 'Check Out'), ('break_start', 'Break Start'), ('break_end', 'Break End')], max_length=20)),
                ('device_id', models.CharField(help_text='ID of the fingerprint device', max_length=100)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('confidence_score', models.IntegerField(default=100, help_text='Confidence score of fingerprint match (0-100)')),
                ('notes', models.TextField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biometric_logs', to='emp_app.employee')),
            ],
            options={
                'verbose_name': 'Biometric Attendance Log',
                'verbose_name_plural': 'Biometric Attendance Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('file', models.FileField(upload_to='employee_documents/%Y/%m/')),
                ('file_size', models.IntegerField(default=0, help_text='File size in bytes')),
                ('file_type', models.CharField(blank=True, max_length=50)),
                ('uploaded_by', models.CharField(help_text='User who uploaded the document', max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expiry_date', models.DateField(blank=True, help_text='For documents that expire (e.g., contracts, certifications)', null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('archived', 'Archived')], default='active', max_length=20)),
                ('is_confidential', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='emp_app.documentcategory')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='emp_app.employee')),
            ],
            options={
                'verbose_name': 'Employee Document',
                'verbose_name_plural': 'Employee Documents',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='FingerprintData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fingerprint_template', models.TextField(help_text='Encoded fingerprint template data')),
                ('fingerprint_image', models.ImageField(blank=True, help_text='Optional fingerprint image', null=True, upload_to='fingerprints/')),
                ('enrolled_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('device_id', models.CharField(blank=True, help_text='ID of the fingerprint device used', max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('quality_score', models.IntegerField(default=0, help_text='Quality score of fingerprint (0-100)')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fingerprint', to='emp_app.employee')),
            ],
            options={
                'verbose_name': 'Fingerprint Data',
                'verbose_name_plural': 'Fingerprint Data',
            },
        ),
    ]
