# Generated by Django 5.1.1 on 2025-10-30 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0004_documentcategory_biometricattendance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='phone_num',
            field=models.BigIntegerField(default=0),
        ),
    ]
